import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale } from 'next-intl/server'
import '@/styles/globals.css'
import { CSSProperties } from 'react'

import { ToggleLanguageButton } from '@/modules/common/ToggleLanguageButton'
import PAGE_URL from '@/shared/constants/page-url'
import { QueryClientProvider } from '@/shared/providers/QueryClientProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const divStyle: CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  gap: 10,
  padding: 20,
  justifyContent: 'center',
  alignItems: 'center',
}

const navStyle: CSSProperties = {
  display: 'flex',
  gap: 10,
  padding: 20,
  justifyContent: 'space-between',
  backgroundColor: 'black',
  color: 'white',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextIntlClientProvider>
          <QueryClientProvider>
            <div>
              <nav style={navStyle}>
                <Link href={PAGE_URL.auth.login}>Login</Link>
                <ToggleLanguageButton />
              </nav>
              <div style={divStyle}>{children}</div>
            </div>
          </QueryClientProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
